name: Deploy to AWS

on:
  # Trigger the workflow when code is pushed to the 'master' branch
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up JDK 11 (Java is required for CDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'  # Corrected to temurin

      # Step 3: Set up Node.js (AWS CDK uses Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 4: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 5: Cache Node.js dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 6: Install dependencies (Java and Node)
      - name: Install Java dependencies
        run: mvn clean install
      - name: Install Java dependencies
        run: mvn package

      - name: Install Node.js dependencies
        run: npm install

      # Step 7: Install AWS CDK CLI and verify installation
      - name: Install AWS CDK CLI
        run: |
          npm install -g aws-cdk
          which cdk  # Check if cdk is installed
          cdk --version  # Check CDK version to ensure it's installed

      # Step 8: Deploy using AWS CDK
      - name: Deploy with CDK
        run: cdk deploy --require-approval never
