name: AWS IoT Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  id-token: write  # ✅ Required for OIDC authentication
  contents: read   # ✅ Allows reading repo contents

jobs:
  deploy:
    name: Deploy AWS IoT Setup
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug GitHub OIDC Token
        run: |
          echo "Requesting OIDC Token..."
          curl -H "Authorization: bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN" \
               "$ACTIONS_ID_TOKEN_REQUEST_URL&audience=sts.amazonaws.com"
        env:
          ACTIONS_ID_TOKEN_REQUEST_TOKEN: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_TOKEN }}
          ACTIONS_ID_TOKEN_REQUEST_URL: ${{ secrets.ACTIONS_ID_TOKEN_REQUEST_URL }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::626635402177:role/GitHubActionRole
          role-session-name: GitHubActions
          aws-region: ap-south-1

      - name: Verify AWS authentication
        run: aws sts get-caller-identity

