name: Deploy to AWS

on:
  # Trigger the workflow when code is pushed to the 'master' branch
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code from GitHub
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up AWS credentials (use secrets to securely pass credentials)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1  # Specify your AWS region here

      # Step 3: Set up JDK 11 (Java is required for CDK)
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'temurin'

      # Step 4: Set up Node.js (AWS CDK uses Node.js)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Step 5: Cache Maven dependencies
      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 6: Cache Node.js dependencies
      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      # Step 7: Install dependencies (Java and Node)
      - name: Install Java dependencies
        run: mvn clean install

      - name: Install Node.js dependencies
        run: npm install

      # Step 8: Install AWS CDK CLI
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # Step 9: Deploy using AWS CDK
      - name: Deploy with CDK
        run: cdk deploy --require-approval never
